# Generated by Django 2.0.1 on 2018-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('ref_firma', models.CharField(max_length=300, verbose_name='Firma')),
                ('ref_adi', models.CharField(max_length=300, verbose_name='Referasn adı')),
                ('ref_teknoloji', models.CharField(max_length=500, verbose_name='Teknolojiler')),
                ('ref_aciklama', models.TextField(blank=True, null=True, verbose_name='Başlık')),
                ('ref_siteurl', models.CharField(max_length=500, verbose_name='Site url')),
                ('ref_resim', models.ImageField(upload_to='', verbose_name='Resim')),
                ('ref_url', models.CharField(max_length=500, verbose_name='Url')),
                ('ref_seo_baslik', models.CharField(blank=True, max_length=70, null=True, verbose_name='seo başlık')),
                ('ref_seo_keywords', models.TextField(blank=True, null=True, verbose_name='Anahtar kelimeler')),
                ('ref_seo_aciklama', models.TextField(blank=True, null=True, verbose_name='Seo Açıklama')),
            ],
        ),
    ]
