# Generated by Django 2.0.1 on 2018-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say_baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('say_adi', models.CharField(max_length=300, verbose_name='Referasn adı')),
                ('say_aciklama', models.TextField(blank=True, null=True, verbose_name='Başlık')),
                ('say_resim', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('say_url', models.CharField(max_length=500, verbose_name='Url')),
                ('say_seo_baslik', models.CharField(blank=True, max_length=70, null=True, verbose_name='seo başlık')),
                ('say_seo_keywords', models.TextField(blank=True, null=True, verbose_name='Anahtar kelimeler')),
                ('say_seo_aciklama', models.TextField(blank=True, null=True, verbose_name='Seo Açıklama')),
            ],
        ),
    ]
