# Generated by Django 2.0.1 on 2018-02-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_sayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_resim', models.ImageField(upload_to='', verbose_name='Resim')),
                ('res_oncelik', models.CharField(max_length=40, verbose_name='Öncelik')),
                ('res_video', models.CharField(blank=True, max_length=70, null=True, verbose_name='video')),
                ('res_referans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Referans', verbose_name='Referans')),
            ],
        ),
    ]
