# Generated by Django 2.0.1 on 2018-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_baslik', models.CharField(blank=True, max_length=70, null=True, verbose_name='seo başlık')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='Anahtar kelimeler')),
                ('seo_aciklama', models.TextField(blank=True, null=True, verbose_name='Seo Açıklama')),
            ],
        ),
    ]
