# Generated by Django 2.0.1 on 2018-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_remove_image_res_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='İsler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_adi', models.CharField(max_length=300, verbose_name='Referasn adı')),
                ('ref_baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('ref_firma', models.CharField(max_length=300, verbose_name='Firma')),
                ('ref_teknoloji', models.CharField(max_length=500, verbose_name='Teknolojiler')),
                ('ref_aciklama', models.TextField(blank=True, null=True, verbose_name='Başlık')),
                ('ref_siteurl', models.CharField(max_length=500, verbose_name='Site url')),
                ('ref_resim', models.ImageField(upload_to='', verbose_name='Resim')),
                ('ref_url', models.CharField(max_length=500, verbose_name='Url')),
                ('ref_seo_baslik', models.CharField(blank=True, max_length=70, null=True, verbose_name='seo başlık')),
                ('ref_seo_keywords', models.TextField(blank=True, null=True, verbose_name='Anahtar kelimeler')),
                ('ref_seo_aciklama', models.TextField(blank=True, null=True, verbose_name='Seo Açıklama')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='res_referans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Referans'),
        ),
    ]
