# Generated by Django 2.0.1 on 2018-03-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20180304_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='res_referans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.İsler'),
        ),
    ]
