# Generated by Django 2.0.1 on 2018-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20180306_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='İletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilt_isim', models.CharField(blank=True, max_length=300, null=True, verbose_name='İsim')),
                ('ilt_firma', models.CharField(blank=True, max_length=300, null=True, verbose_name='Firma')),
                ('ilt_telefon', models.CharField(blank=True, max_length=300, null=True, verbose_name='Telefon')),
                ('ilt_eposta', models.CharField(blank=True, max_length=300, null=True, verbose_name='Eposta')),
                ('ilt_turu', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tür')),
                ('ilt_mesaj', models.TextField(blank=True, null=True, verbose_name='İçerik')),
                ('ilt_durum', models.CharField(blank=True, choices=[(1, 'Okundu'), (2, 'Okunmadı')], max_length=300, null=True, verbose_name='durum')),
            ],
        ),
    ]
